#语言对应声卡名字
yyq:
  chinese: cn
  chineseKEY: cn
  english: en
  englishKEY: en
  other: other
  #各个端口号
  adminUrl: 6489
  #接口对应启动地址
  asrUrl: 8777
  asrUrlKEY: asrUrl
  audioUrlCN: 4567
  audioUrlCNKEY: audioUrlCN
  audioUrlEN: 7654
  audioUrlENKEY: audioUrlEN
  audioUrlKEY: audioUrl
  webUrl: 8002
  webUrlKEY: webUrl
  serverUrl: 8008
  serverUrlKEY: serverUrl
  UDPPortCN: 6600
  UDPPortEN: 6601
  TCPPort: 6602
  #后台管理地址
  adminAddress: 182.150.56.46
  #接口返回值名字
  jsonName: soundcardName
  jsonNameType: langType
  #接口返回值所对应类型的值
  jsonNameTypeChineseValue: CN
  jsonNameTypeEnglishValue: EN
  jsonNameTypeOtherValue: OTHER
  #接口对应启动地址
  addressOpen: http://127.0.0.1:8777/  recognition_open
  #接口对应关闭地址
  addressClose: http://127.0.0.1:8777/  recognition_close
  #文件生成接口地址
  fileAddressOpen: http://127.0.0.1:8777/  config
  #websockeet局域网地址
  addressOpenLANEN: http://127.0.0.1:7654/open_audio
  addressOpenLANCN: http://127.0.0.1:4567/open_audio
  addressCloseLANEN: http://127.0.0.1:7654/close_audio
  addressCloseLANCN: http://127.0.0.1:4567/close_audio
  #udp4g语音传输
  addressOpenWEBCN: http://127.0.0.1:6511/udp/start_cn
  addressOpenWEBEN: http://127.0.0.1:6501/udp/start_en
  addressCloseWEBCN: http://127.0.0.1:6511/udp/close_cn
  addressCloseWEBEN: http://127.0.0.1:6501/udp/close_en
  #与前端交互的json生成地址
  addressJson: D:/  nginx/html
  #服务器开启地址
  startNginxAddress: D:/  nginx
  #服务器开启文件
  startFile: startNginx.bat
  #服务器关闭地址
  stopNginxAddress: D:/  nginx
  #服务器关闭文件
  stopFile: stopNginx.bat
  #录制音频与识别文字存储文件名
  recordAddress: D:/  file
  #jar存储位置
  jarAddress: D:/  jar
  #文件生成路径
  filePath: ""
  #登录路径
  admin: http://ak.lan-bridge.cn:6488
  adminKEY: adminUrl
  #文件路径
  fileUrl: http://ak.lan-bridge.cn:2356
  fileUrlKEY: fileUrl
  #声卡数量
  speechNumber: 2
  #会议id
  meetingId:
  #true为4g false为局域网
  status: true
  #4G网络传输地址
  InternetURL: ak.lan-bridge.cn
  #TCP开启关闭接口
  TCPOpenURL: http://192.168.2.201:6500/tcp/start
  TCPCloseURL: http://192.168.2.201:6500/tcp/close
